theme: jekyll-theme-minimal

plugins:
   - jekyll-mentions
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   
collections:
  faq:
    output: false
  faq_categories:
    output: false
  glossary:
    output: false
  blog:
    output: true
  docs:
    output: true
